spring:
  application:
    name: second hand transaction
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: youpassword
    url: jdbc:mysql://localhost:3306/comp_7506
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
server:
  port: 9014
