spring:
  application:
    name: second hand transaction
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/comp_7506
server:
  port: 9012
logging:
  config: classpath:log4j2-dev.xml
